services:
  - type: web
    name: jmx-motorsport
    runtime: python
    pythonVersion: "3.12.3"
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: motorsport_db
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
    healthCheckPath: /health
